### ISSUE TITLE
little issue with evaluate_accuracy

### ISSUE THREAD

**Issue by malhotrachetan** [ThomasDelteil/HandwrittenTextRecognition_MXNet#1]
![screen shot 2018-05-03 at 12 54 36 am](https://user-images.githubusercontent.com/13315992/39544792-d51b052e-4e6c-11e8-91be-cdcf40ec1ebc.png)

I am getting this error. I am a beginner with mxnet, it would be so great if you could help or direct me. Thanks a ton

**Comment by ThomasDelteil** [comment]
Hi @debuggermalhotra , the reason would be that your `dataloader` here is not holding any data, which is probably your real bug. If you want to fix this specific bug, set `i = 0` after `metric = 0`. But you should be really looking at why your `dataloader` is empty.

**Comment by malhotrachetan** [comment]
Guess, was my bad. Trying to move forward too quickly without even noticing that dataloader is not yet filled. Anyway thanks a ton for your help. Great work btw!!
