### ISSUE TITLE
what is this global variable 'NUM_CLASSES' in lstm_ocr_ctc?

### ISSUE THREAD

**Issue by wangx404** [ThomasDelteil/HandwrittenTextRecognition_MXNet#19]
In `lstm_ocr_ctc.ipynb`, this is a global variable `NUM_CLASSES`, but it was not used. So is there something wrong here?

**Comment by wangx404** [comment]
I find another probelem. In l`ine_segmentation.ipynb`, after defining the SSD network, you invoke in like `SSD(2)`. However, when we dive into the network structure, we can find this statement `gluon.nn.Conv2D(num_anchors_predicted*(self.num_classes + 1)`. According to original define, this is **wrong**! Either you add another one class to calculate num_classes, or you add one in defining the cnn network.

**Comment by jonomon** [comment]
Hi @wangx404,

Thank you for pointing this out. 

For the first point, lstm_ocr_ctc.ipynb is actually outdated and will be removed in future versions. Please refer to handwriting_ocr.ipynb for a more up to date version of handwriting recognition.

For the second point, thank you so much. We will look into this!

**Comment by ThomasDelteil** [comment]
@wangx404 I deleted the old outdated file for clarity, please refer indeed to `handwriting_ocr.ipynb`
