### ISSUE TITLE
Pretrained Model word_segmentation2.params

### ISSUE THREAD

**Issue by gipfelen** [ThomasDelteil/HandwrittenTextRecognition_MXNet#20]
The pertained model word_segmentation2.params, which is used in https://github.com/ThomasDelteil/HandwrittenTextRecognition_MXNet/blob/master/handwriting_ocr.ipynb is not available for download.

**Comment by PotatoSpudowski** [comment]
Did you find a workaround for this?

**Comment by ThomasDelteil** [comment]
I'll upload it tonight

**Comment by ThomasDelteil** [comment]
It has been uploaded you can find the link in the README.md 😃
