### ISSUE TITLE
Unable to replicate the results

### ISSUE THREAD

**Issue by PotatoSpudowski** [ThomasDelteil/HandwrittenTextRecognition_MXNet#21]
Hi I used the same code and param values that were there in the downloads section. I am unable to replicate your results.

![screenshot from 2019-01-05 22-53-46](https://user-images.githubusercontent.com/29813400/50727197-a32fb200-113d-11e9-819c-e91c4d9114f9.png)

The bounding boxes are always in the same position no mater the image. Can you please lemme know if the handwriting_ocr.ipynb is giving the same problems to you.

**Comment by ThomasDelteil** [comment]
It isn't giving me the same problem, the results are correctly segmented. Maybe you are preprocessing the images differently? Make sure to check the preprocessing functions and that they match the ones used during training.

**Comment by PotatoSpudowski** [comment]
Thanks I'll look into it
